//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Project1.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class formalize_order
    {
        public int Id { get; set; }
        public string name_order { get; set; }
        public string FIO { get; set; }
        public string vk { get; set; }
        public string comment { get; set; }
        public string working_fio { get; set; }
        public Nullable<int> progress_order { get; set; }
        public string phone { get; set; }
    }
}
