//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Project1.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public int ID_COMPANY { get; set; }
        public string SALARY { get; set; }
    
        public virtual Users_Data Users_Data { get; set; }
    }
}
